postgresCfg:
  host: localhost
  port: 5432
  database: trajimpu
  user: admin
  password: secret

trafficForceProviderCfg:
  start_date: 2024-01-01
  end_date: 2024-01-07
  date_step: 1
  base_tile_size_m: 50
  down_scale_factor: 16
  area:
    bottom_left:
      E: 3592900.0
      N: 3055500.0
    top_right:
      E: 4399500.0
      N: 3475350.0
  vessel_types: ['cargo', 'tanker']
  output_dir: "Outputs/Traffic"
  sato_sigmas: [4, 8, 16, 32]
  gaussian_sigma: 32
  low_percentile_cutoff: 1.0
  high_percentile_cutoff: 99
  sensitivity1: 0.5
  sensitivity2: 1

depthForceProviderCfg:
  down_scale_factor: 16
  area:
    bottom_left:
      E: 3592900.0
      N: 3055500.0
    top_right:
      E: 4399500.0
      N: 3475350.0
  output_dir: "Outputs/Depth"
  gaussian_sigma: 4
  low_percentile_cutoff: 0
  high_percentile_cutoff: 50
  sensitivity1: 2
  sensitivity2: 2


heatmapGeneratorCfg:
  output_dir: "Outputs/Heatmaps"
  target_pixel_size: 4000
  color_map: 'jet' # Options: 'plasma', 'viridis', 'inferno', 'jet'

modelDataCfg:
  area: "string"
  num_workers: 30
  output_dir: "Data"

modelDataLoaderCfg:
  batch_size: 64
  shuffle: true
  num_workers: 4
  train_split: 0.8 # Proportion of data used for training
  start_date: 2024-03-01
  end_date: 2024-03-02
  date_step: 1

modelDataProcessorCfg:
  min_len: 10
  max_len: 100
  output_dir: "Data"
  masking_strategy: "POINT_MISSING"
  masking_percentage: 0.1